[features]
seeds = false
skip-lint = false

[programs.localnet]
mint = "EYMs5Mm5vTuUjxR9R5AvAZCBDK5SJc9tDXVa164ZxSbc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"